COUNTRY_KEY_VALUES = {
    "afghanistan": "Afghanistan",
    "albania": "Albania",
    "algeria": "Algeria",
    "andorra": "Andorra",
    "angola": "Angola",
    "argentina": "Argentina",
    "armenia": "Armenia",
    "australia": "Australia",
    "austria": "Austria",
    "azerbaijan": "Azerbaijan",
    "bahamas": "Bahamas",
    "bangladesh": "Bangladesh",
    "belarus": "Belarus",
    "belgium": "Belgium",
    "belize": "Belize",
    "benin": "Benin",
    "bhutan": "Bhutan",
    "bolivia": "Bolivia",
    "bosnia_and_herzegovina": "Bosnia and Herzegovina",
    "botswana": "Botswana",
    "brazil": "Brazil",
    "brunei_darussalam": "Brunei Darussalam",
    "bulgaria": "Bulgaria",
    "burkina_faso": "Burkina Faso",
    "burundi": "Burundi",
    "cambodia": "Cambodia",
    "cameroon": "Cameroon",
    "canada": "Canada",
    "central_african_republic": "Centrl African Republic",
    "chad": "Chad",
    "chile": "Chile",
    "china": "China",
    "colombia": "Colombia",
    "congo": "Congo",
    "costa_rica": "Costa Rica",
    "croatia": "Croatia",
    "cuba": "Cuba",
    "cyprus": "Cyprus",
    "czech_republic": "Czech Republic",
    "democratic_republic_of_congo": "Democratic Republic of Congo",
    "denmark": "Denmark",
    "djibouti": "Djibouti",
    "dominican_republic": "Dominican Republic",
    "ecuador": "Ecuador",
    "egypt": "Egypt",
    "el_salvador": "El Salvador",
    "equatorial_guinea": "Equatorial Guinea",
    "eritrea": "Eritrea",
    "estonia": "Estonia",
    "eswatini": "Eswatini",
    "ethiopia": "Ethiopia",
    "falkland_islands_(malvinas)": "Falkland Islands (Malvinas)",
    "fiji": "Fiji",
    "finland": "Finland",
    "france": "France",
    "gabon": "Gabon",
    "gambia": "Gambia",
    "georgia": "Georgia",
    "germany": "Germany",
    "ghana": "Ghana",
    "greece": "Greece",
    "greenland": "Greenland",
    "grenada": "Grenada",
    "guadeloupe": "Guadeloupe",
    "guatemala": "Guatemala",
    "guinea": "Guinea",
    "guinea-bissau": "Guinea-Bissau",
    "guyana": "Guyana",
    "haiti": "Haiti",
    "honduras": "Honduras",
    "hong_kong,_china": "Hong Kong, China",
    "hungary": "Hungary",
    "iceland": "Iceland",
    "india": "India",
    "indonesia": "Indonesia",
    "iran": "Iran",
    "iraq": "Iraq",
    "ireland": "Ireland",
    "israel": "Israel",
    "italy": "Italy",
    "ivory_coast": "Ivory Coast",
    "jamaica": "Jamaica",
    "japan": "Japan",
    "jordan": "Jordan",
    "kazakhstan": "Kazakhstan",
    "kenya": "Kenya",
    "kosovo": "Kosovo",
    "kuwait": "Kuwait",
    "kyrgyzstan": "Kyrgyzstan",
    "laos": "Laos",
    "latvia": "Latvia",
    "lebanon": "Lebanon",
    "lesotho": "Lesotho",
    "liberia": "Liberia",
    "libyan_arab_jamahiriya": "Libyan Arab Jamahiriya",
    "lithuania": "Lithuania",
    "luxembourg": "Luxembourg",
    "madagascar": "Madagascar",
    "malawi": "Malawi",
    "malaysia": "Malaysia",
    "mali": "Mali",
    "mauritania": "Mauritania",
    "mauritius": "Mauritius",
    "mexico": "Mexico",
    "moldova": "Moldova",
    "mongolia": "Mongolia",
    "montenegro": "Montenegro",
    "morocco": "Morocco",
    "mozambique": "Mozambique",
    "myanmar": "Myanmar",
    "namibia": "Namibia",
    "nepal": "Nepal",
    "netherlands": "Netherlands",
    "new_caledonia": "New Caledonia",
    "new_zealand": "New Zealand",
    "nicaragua": "Nicaragua",
    "niger": "Niger",
    "nigeria": "Nigeria",
    "north_korea": "North Korea",
    "north_macedonia": "North Macedonia",
    "norway": "Norway",
    "oman": "Oman",
    "pakistan": "Pakistan",
    "panama": "Panama",
    "papua_new_guinea": "Papua New Guinea",
    "paraguay": "Paraguay",
    "peru": "Peru",
    "philippines": "Philippines",
    "poland": "Poland",
    "portugal": "Portugal",
    "puerto_rico": "Puerto Rico",
    "qatar": "Qatar",
    "romania": "Romania",
    "russia": "Russia",
    "rwanda": "Rwanda",
    "saudi_arabia": "Saudi Arabia",
    "senegal": "Senegal",
    "serbia": "Serbia",
    "sierra_leone": "Sierra Leone",
    "singapore": "Singapore",
    "slovakia": "Slovakia",
    "slovenia": "Slovenia",
    "solomon_islands": "Solomon Islands",
    "somalia": "Somalia",
    "south_africa": "South Africa",
    "south_korea": "South Korea",
    "spain": "Spain",
    "sri_lanka": "Sri Lanka",
    "sudan": "Sudan",
    "suriname": "Suriname",
    "sweden": "Sweden",
    "switzerland": "Switzerland",
    "syria": "Syria",
    "taiwan,_china": "Taiwan, China",
    "tajikistan": "Tajikistan",
    "tanzania": "Tanzania",
    "thailand": "Thailand",
    "timor_leste": "Timor Leste",
    "togo": "Togo",
    "trinidad_and_tobago": "Trinidad and Tobago",
    "tunisia": "Tunisia",
    "turkmenistan": "Turkmenistan",
    "türkiye": "Türkiye",
    "uganda": "Uganda",
    "ukraine": "Ukraine",
    "united_arab_emirates": "United Arab Emirates",
    "united_kingdom": "United Kingdom",
    "united_states": "United States",
    "uruguay": "Uruguay",
    "uzbekistan": "Uzbekistan",
    "vanuatu": "Vanuatu",
    "vatican_city": "Vatican City",
    "venezuela": "Venezuela",
    "vietnam": "Vietnam",
    "yemen": "Yemen",
    "zambia": "Zambia",
    "zimbabwe": "Zimbabwe",
}

ISO_KEY_VALUES = {
    "ae": "AE",
    "af": "AF",
    "al": "AL",
    "am": "AM",
    "an": "AN",
    "ao": "AO",
    "ar": "AR",
    "at": "AT",
    "au": "AU",
    "az": "AZ",
    "ba": "BA",
    "bd": "BD",
    "be": "BE",
    "bf": "BF",
    "bg": "BG",
    "bi": "BI",
    "bj": "BJ",
    "bn": "BN",
    "bo": "BO",
    "br": "BR",
    "bs": "BS",
    "bt": "BT",
    "bw": "BW",
    "by": "BY",
    "bz": "BZ",
    "ca": "CA",
    "cd": "CD",
    "cf": "CF",
    "cg": "CG",
    "ch": "CH",
    "ci": "CI",
    "cl": "CL",
    "cm": "CM",
    "cn": "CN",
    "co": "CO",
    "cr": "CR",
    "cu": "CU",
    "cy": "CY",
    "cz": "CZ",
    "de": "DE",
    "dj": "DJ",
    "dk": "DK",
    "do": "DO",
    "dz": "DZ",
    "ec": "EC",
    "ee": "EE",
    "eg": "EG",
    "er": "ER",
    "es": "ES",
    "et": "ET",
    "fi": "FI",
    "fj": "FJ",
    "fk": "FK",
    "fr": "FR",
    "ga": "GA",
    "gb": "GB",
    "gd": "GD",
    "ge": "GE",
    "gh": "GH",
    "gl": "GL",
    "gm": "GM",
    "gn": "GN",
    "gp": "GP",
    "gq": "GQ",
    "gr": "GR",
    "gt": "GT",
    "gw": "GW",
    "gy": "GY",
    "hk": "HK",
    "hn": "HN",
    "hr": "HR",
    "ht": "HT",
    "hu": "HU",
    "id": "ID",
    "ie": "IE",
    "il": "IL",
    "in": "IN",
    "iq": "IQ",
    "ir": "IR",
    "is": "IS",
    "it": "IT",
    "jm": "JM",
    "jo": "JO",
    "jp": "JP",
    "ke": "KE",
    "kg": "KG",
    "kh": "KH",
    "kp": "KP",
    "kr": "KR",
    "kw": "KW",
    "kz": "KZ",
    "la": "LA",
    "lb": "LB",
    "li": "LI",
    "lk": "LK",
    "lr": "LR",
    "ls": "LS",
    "lt": "LT",
    "lu": "LU",
    "lv": "LV",
    "ly": "LY",
    "ma": "MA",
    "md": "MD",
    "me": "ME",
    "mg": "MG",
    "mh": "MH",
    "mk": "MK",
    "ml": "ML",
    "mm": "MM",
    "mn": "MN",
    "mr": "MR",
    "mt": "MT",
    "mu": "MU",
    "mw": "MW",
    "mx": "MX",
    "my": "MY",
    "mz": "MZ",
    "na": "NA",
    "nc": "NC",
    "ne": "NE",
    "ng": "NG",
    "ni": "NI",
    "nl": "NL",
    "no": "NO",
    "np": "NP",
    "nu": "NU",
    "nz": "NZ",
    "om": "OM",
    "pa": "PA",
    "pe": "PE",
    "pg": "PG",
    "ph": "PH",
    "pk": "PK",
    "pl": "PL",
    "pr": "PR",
    "pt": "PT",
    "py": "PY",
    "qa": "QA",
    "re": "RE",
    "ro": "RO",
    "rs": "RS",
    "ru": "RU",
    "rw": "RW",
    "sa": "SA",
    "sb": "SB",
    "sd": "SD",
    "se": "SE",
    "sg": "SG",
    "si": "SI",
    "sk": "SK",
    "sl": "SL",
    "sn": "SN",
    "so": "SO",
    "sr": "SR",
    "sv": "SV",
    "sy": "SY",
    "sz": "SZ",
    "td": "TD",
    "tg": "TG",
    "th": "TH",
    "tj": "TJ",
    "tl": "TL",
    "tm": "TM",
    "tn": "TN",
    "tr": "TR",
    "tt": "TT",
    "tv": "TV",
    "tw": "TW",
    "tz": "TZ",
    "ua": "UA",
    "ug": "UG",
    "us": "US",
    "uy": "UY",
    "uz": "UZ",
    "va": "VA",
    "ve": "VE",
    "vn": "VN",
    "vu": "VU",
    "xk": "XK",
    "ye": "YE",
    "za": "ZA",
    "zm": "ZM",
    "zw": "ZW",
}
